PKGDIR=../..
<$PKGDIR/mkconfig


DIRS=\
	t\

<$PKGDIR/mkfiles/mksubdirs


DISBIN=$PKGDIR/dis/lib

TARG=\
	growing.dis\

SYSMODULES=\

OPTMODULES=\

MODULES=\
	$PKGDIR/module/growing.m\

<$PKGDIR/mkfiles/mkdis
