PKGDIR=../../..
<$PKGDIR/mkconfig


TESTS=\
	smoke.dis\
	all.dis\
	examples.dis\

TESTTARG=\

SYSMODULES=\
	sys.m\
	draw.m\

OPTMODULES=\
	opt/powerman/tap/module/t.m\
	opt/powerman/tap/module/tap.m\

MODULES=\
	$PKGDIR/module/growing.m\

<$PKGDIR/mkfiles/mktest
